export const componentGroups = [
  {
    id: 'token-style',
    title: 'Token / 样式',
  },
  {
    id: 'surface-material',
    title: 'Surface / 材质',
  },
  {
    id: 'controls-overlays',
    title: '控件 / 弹层',
  },
  {
    id: 'layout-bars',
    title: '布局 / 栏位',
  },
  {
    id: 'tags-navigation',
    title: '标签 / 导航',
  },
  {
    id: 'content-markdown',
    title: '内容 / Markdown',
  },
  {
    id: 'media-ocr',
    title: '媒体 / OCR',
  },
  {
    id: 'data-visualization',
    title: '数据 / 可视化',
  },
] as const

export type ComponentGroupId = (typeof componentGroups)[number]['id']

export type PublicComponentManifestItem = {
  id: string
  name: string
  exportName?: string
  registryName: string
  packageExport: string
  group: ComponentGroupId
  docs: boolean
  registry: true
}

export type ComponentManifestItem = PublicComponentManifestItem

export const componentManifest = [
  {
    id: 'component-preview-card',
    name: 'ComponentPreviewCard',
    registryName: 'component-preview-card',
    packageExport: './components/component-preview-card',
    group: 'token-style',
    docs: false,
    registry: true,
  },
  {
    id: 'md',
    name: 'Markdown渲染',
    exportName: 'Md',
    registryName: 'md',
    packageExport: './components/md',
    group: 'token-style',
    docs: true,
    registry: true,
  },
  {
    id: 'text-color',
    name: '字色',
    registryName: 'text-color',
    packageExport: './components/text-color',
    group: 'token-style',
    docs: false,
    registry: true,
  },
  {
    id: 'pressable',
    name: '按压反馈色',
    registryName: 'pressable',
    packageExport: './components/pressable',
    group: 'token-style',
    docs: false,
    registry: true,
  },
  {
    id: 'text-tokens',
    name: '文字',
    registryName: 'font-size',
    packageExport: './components/font-size',
    group: 'token-style',
    docs: true,
    registry: true,
  },
  {
    id: 'heat-color',
    name: '热力图色',
    registryName: 'heat-color',
    packageExport: './components/heat-color',
    group: 'token-style',
    docs: false,
    registry: true,
  },
  {
    id: 'background-tokens',
    name: '背景',
    registryName: 'bg-color',
    packageExport: './components/bg-color',
    group: 'token-style',
    docs: true,
    registry: true,
  },
  {
    id: 'bg-blur',
    name: '背景模糊度',
    registryName: 'bg-blur',
    packageExport: './components/bg-blur',
    group: 'token-style',
    docs: false,
    registry: true,
  },
  {
    id: 'border-tokens',
    name: '边框',
    registryName: 'border-color',
    packageExport: './components/border-color',
    group: 'token-style',
    docs: true,
    registry: true,
  },
  {
    id: 'border-radius',
    name: '边框圆角',
    registryName: 'border-radius',
    packageExport: './components/border-radius',
    group: 'token-style',
    docs: false,
    registry: true,
  },
  {
    id: 'glass-surface',
    name: 'GlassSurface',
    registryName: 'glass-surface',
    packageExport: './components/glass-surface',
    group: 'surface-material',
    docs: false,
    registry: true,
  },
  {
    id: 'popup-surface',
    name: 'PopupSurface',
    registryName: 'popup-surface',
    packageExport: './components/popup-surface',
    group: 'surface-material',
    docs: false,
    registry: true,
  },
  {
    id: 'surface',
    name: 'Surface',
    registryName: 'card-surface',
    packageExport: './components/card-surface',
    group: 'surface-material',
    docs: true,
    registry: true,
  },
  {
    id: 'action-dialog',
    name: 'ActionDialog',
    registryName: 'action-dialog',
    packageExport: './components/action-dialog',
    group: 'controls-overlays',
    docs: true,
    registry: true,
  },
  {
    id: 'ghost-icon-button',
    name: 'GhostIconButton',
    registryName: 'ghost-icon-button',
    packageExport: './components/ghost-icon-button',
    group: 'controls-overlays',
    docs: false,
    registry: true,
  },
  {
    id: 'glass-icon-button',
    name: 'GlassIconButton',
    registryName: 'glass-icon-button',
    packageExport: './components/glass-icon-button',
    group: 'controls-overlays',
    docs: false,
    registry: true,
  },
  {
    id: 'menu',
    name: 'Menu',
    registryName: 'menu',
    packageExport: './components/menu',
    group: 'controls-overlays',
    docs: true,
    registry: true,
  },
  {
    id: 'mode-button',
    name: 'ModeButton',
    registryName: 'mode-button',
    packageExport: './components/mode-button',
    group: 'controls-overlays',
    docs: false,
    registry: true,
  },
  {
    id: 'button',
    name: '按钮',
    exportName: 'TextButton',
    registryName: 'text-button',
    packageExport: './components/text-button',
    group: 'controls-overlays',
    docs: true,
    registry: true,
  },
  {
    id: 'bottom-bar',
    name: 'BottomBar',
    registryName: 'bottom-bar',
    packageExport: './components/bottom-bar',
    group: 'layout-bars',
    docs: false,
    registry: true,
  },
  {
    id: 'card-tool-bar',
    name: 'CardToolBar',
    registryName: 'card-tool-bar',
    packageExport: './components/card-tool-bar',
    group: 'layout-bars',
    docs: false,
    registry: true,
  },
  {
    id: 'card-top-bar',
    name: 'CardTopBar',
    registryName: 'card-top-bar',
    packageExport: './components/card-top-bar',
    group: 'layout-bars',
    docs: false,
    registry: true,
  },
  {
    id: 'sidebar',
    name: 'SideBar',
    registryName: 'sidebar',
    packageExport: './components/sidebar',
    group: 'layout-bars',
    docs: false,
    registry: true,
  },
  {
    id: 'top-bar',
    name: 'TopBar',
    registryName: 'top-bar',
    packageExport: './components/top-bar',
    group: 'layout-bars',
    docs: false,
    registry: true,
  },
  {
    id: 'bar',
    name: '浮动栏',
    exportName: 'FloatBar',
    registryName: 'float-bar',
    packageExport: './components/float-bar',
    group: 'layout-bars',
    docs: true,
    registry: true,
  },
  {
    id: 'chip-button',
    name: 'ChipButton',
    registryName: 'chip-button',
    packageExport: './components/chip-button',
    group: 'tags-navigation',
    docs: false,
    registry: true,
  },
  {
    id: 'tag-bread',
    name: 'TagBread',
    registryName: 'tag-bread',
    packageExport: './components/tag-bread',
    group: 'tags-navigation',
    docs: false,
    registry: true,
  },
  {
    id: 'tag-picker',
    name: 'TagPicker',
    registryName: 'tag-picker',
    packageExport: './components/tag-picker',
    group: 'tags-navigation',
    docs: false,
    registry: true,
  },
  {
    id: 'tag-tree',
    name: 'TagTree',
    registryName: 'tag-tree',
    packageExport: './components/tag-tree',
    group: 'tags-navigation',
    docs: false,
    registry: true,
  },
  {
    id: 'tag-tree-row',
    name: 'TagTreeRow',
    registryName: 'tag-tree-row',
    packageExport: './components/tag-tree-row',
    group: 'tags-navigation',
    docs: false,
    registry: true,
  },
  {
    id: 'tag',
    name: '标签',
    exportName: 'TagBar',
    registryName: 'tag-bar',
    packageExport: './components/tag-bar',
    group: 'tags-navigation',
    docs: true,
    registry: true,
  },
  {
    id: 'capsule',
    name: '胶囊',
    exportName: 'Chip',
    registryName: 'chip',
    packageExport: './components/chip',
    group: 'tags-navigation',
    docs: true,
    registry: true,
  },
  {
    id: 'card',
    name: 'Card',
    registryName: 'card',
    packageExport: './components/card',
    group: 'content-markdown',
    docs: true,
    registry: true,
  },
  {
    id: 'card-composer',
    name: 'CardComposer',
    registryName: 'card-composer',
    packageExport: './components/card-composer',
    group: 'content-markdown',
    docs: true,
    registry: true,
  },
  {
    id: 'math-editor',
    name: 'MathEditor',
    registryName: 'math-editor',
    packageExport: './components/math-editor',
    group: 'content-markdown',
    docs: true,
    registry: true,
  },
  {
    id: 'md-editor',
    name: 'MdEditor',
    registryName: 'md-editor',
    packageExport: './components/md-editor',
    group: 'content-markdown',
    docs: true,
    registry: true,
  },
  {
    id: 'md-render',
    name: 'MdRender',
    registryName: 'md-render',
    packageExport: './components/md-render',
    group: 'content-markdown',
    docs: true,
    registry: true,
  },
  {
    id: 'md-view',
    name: 'MdView',
    registryName: 'md-view',
    packageExport: './components/md-view',
    group: 'content-markdown',
    docs: true,
    registry: true,
  },
  {
    id: 'canvas-transparency',
    name: 'CanvasTransparency',
    registryName: 'canvas-transparency',
    packageExport: './components/canvas-transparency',
    group: 'media-ocr',
    docs: true,
    registry: true,
  },
  {
    id: 'image-uploader',
    name: 'ImageUploader',
    registryName: 'image-uploader',
    packageExport: './components/image-uploader',
    group: 'media-ocr',
    docs: true,
    registry: true,
  },
  {
    id: 'image-view',
    name: 'ImageView',
    registryName: 'image-view',
    packageExport: './components/image-view',
    group: 'media-ocr',
    docs: true,
    registry: true,
  },
  {
    id: 'ocr-card',
    name: 'OcrCard',
    registryName: 'ocr-card',
    packageExport: './components/ocr-card',
    group: 'media-ocr',
    docs: true,
    registry: true,
  },
  {
    id: 'ocr-composer',
    name: 'OcrComposer',
    registryName: 'ocr-composer',
    packageExport: './components/ocr-composer',
    group: 'media-ocr',
    docs: true,
    registry: true,
  },
  {
    id: 'ocr-detail',
    name: 'OcrDetail',
    registryName: 'ocr-detail',
    packageExport: './components/ocr-detail',
    group: 'media-ocr',
    docs: true,
    registry: true,
  },
  {
    id: 'heatmap',
    name: 'Heatmap',
    registryName: 'heatmap',
    packageExport: './components/heatmap',
    group: 'data-visualization',
    docs: true,
    registry: true,
  },
  {
    id: 'stat-group',
    name: 'StatGroup',
    registryName: 'stat-group',
    packageExport: './components/stat-group',
    group: 'data-visualization',
    docs: true,
    registry: true,
  },
] as const satisfies ComponentManifestItem[]

export type ComponentId = Extract<
  (typeof componentManifest)[number],
  { readonly docs: true }
>['id']
