// Generated by scripts/sync-component-catalog.mjs. Do not edit directly.
import { textTokensDefinition } from './packages/weimo-ui-core/text-tokens'
import { backgroundTokensDefinition } from './packages/weimo-ui-core/background-tokens'
import { borderTokensDefinition } from './packages/weimo-ui-core/border-tokens'
import { surfaceDefinition } from './packages/weimo-ui-core/surface'
import { buttonDefinition } from './packages/weimo-ui-core/button'
import { capsuleButtonDefinition } from './packages/weimo-ui-core/capsule-button'
import { labeledSwitchDefinition } from './packages/weimo-ui-core/labeled-switch'
import { sliderDefinition } from './packages/weimo-ui-core/slider'
import { menuDefinition } from './packages/weimo-ui-core/menu'
import { actionDialogDefinition } from './packages/weimo-ui-core/action-dialog'
import { barDefinition } from './packages/weimo-ui-core/bar'
import { sidebarDefinition } from './packages/weimo-ui-core/sidebar'
import { tagBreadDefinition } from './packages/weimo-ui-tagtree/tag-bread'
import { tagDefinition } from './packages/weimo-ui-tagtree/tag'
import { markdownDefinition } from './packages/weimo-ui-markdown/markdown'
import { imageDefinition } from './packages/weimo-ui-image/image'
import { statDefinition } from './packages/weimo-ui-stats/stat'
import { baseCardDefinition } from './packages/weimo-ui-card/base-card'
import { componentPreviewCardDefinition } from './packages/weimo-ui-card/component-preview-card'
import { cardToolBarDefinition } from './packages/weimo-ui-card/card-tool-bar'
import { taggedCardDefinition } from './packages/weimo-ui-card/tagged-card'
import { tagBarDefinition } from './packages/weimo-ui-card/tag-bar'
import { ocrDefinition } from './packages/weimo-ui-card/ocr'
import type { ComponentId } from './manifest'
import type { ComponentDefinition } from './types'

export const componentDefinitionsById = {
  'text-tokens': textTokensDefinition,
  'background-tokens': backgroundTokensDefinition,
  'border-tokens': borderTokensDefinition,
  surface: surfaceDefinition,
  button: buttonDefinition,
  'capsule-button': capsuleButtonDefinition,
  'labeled-switch': labeledSwitchDefinition,
  slider: sliderDefinition,
  menu: menuDefinition,
  'action-dialog': actionDialogDefinition,
  bar: barDefinition,
  sidebar: sidebarDefinition,
  'tag-bread': tagBreadDefinition,
  tag: tagDefinition,
  markdown: markdownDefinition,
  image: imageDefinition,
  stat: statDefinition,
  'base-card': baseCardDefinition,
  'component-preview-card': componentPreviewCardDefinition,
  'card-tool-bar': cardToolBarDefinition,
  'tagged-card': taggedCardDefinition,
  'tag-bar': tagBarDefinition,
  ocr: ocrDefinition,
} satisfies Record<ComponentId, ComponentDefinition>
