// Generated by scripts/sync-component-catalog.mjs. Do not edit directly.
import { textTokensDefinition } from './packages/weimo-ui-core/text-tokens'
import { backgroundTokensDefinition } from './packages/weimo-ui-core/background-tokens'
import { borderTokensDefinition } from './packages/weimo-ui-core/border-tokens'
import { surfaceDefinition } from './packages/weimo-ui-core/surface'
import { buttonDefinition } from './packages/weimo-ui-core/button'
import { capsuleDefinition } from './packages/weimo-ui-core/capsule'
import { sliderDefinition } from './packages/weimo-ui-core/slider'
import { menuDefinition } from './packages/weimo-ui-core/menu'
import { actionDialogDefinition } from './packages/weimo-ui-core/action-dialog'
import { barDefinition } from './packages/weimo-ui-core/bar'
import { pageLayoutDefinition } from './packages/weimo-ui-core/page-layout'
import { cardToolBarDefinition } from './packages/weimo-ui-core/card-tool-bar'
import { baseCardDefinition } from './packages/weimo-ui-core/base-card'
import { componentPreviewCardDefinition } from './packages/weimo-ui-core/component-preview-card'
import { tagDefinition } from './packages/weimo-ui-tagtree/tag'
import { chipButtonDefinition } from './packages/weimo-ui-tagtree/chip-button'
import { markdownDefinition } from './packages/weimo-ui-markdown/markdown'
import { mdDefinition } from './packages/weimo-ui-markdown/md'
import { imageDefinition } from './packages/weimo-ui-image/image'
import { statDefinition } from './packages/weimo-ui-stats/stat'
import { taggedCardDefinition } from './packages/weimo-ui-card/tagged-card'
import { ocrDefinition } from './packages/weimo-ui-card/ocr'
import type { ComponentId } from './manifest'
import type { ComponentDefinition } from './types'

export const componentDefinitionsById = {
  'text-tokens': textTokensDefinition,
  'background-tokens': backgroundTokensDefinition,
  'border-tokens': borderTokensDefinition,
  surface: surfaceDefinition,
  button: buttonDefinition,
  capsule: capsuleDefinition,
  slider: sliderDefinition,
  menu: menuDefinition,
  'action-dialog': actionDialogDefinition,
  bar: barDefinition,
  'page-layout': pageLayoutDefinition,
  'card-tool-bar': cardToolBarDefinition,
  'base-card': baseCardDefinition,
  'component-preview-card': componentPreviewCardDefinition,
  tag: tagDefinition,
  'chip-button': chipButtonDefinition,
  markdown: markdownDefinition,
  md: mdDefinition,
  image: imageDefinition,
  stat: statDefinition,
  'tagged-card': taggedCardDefinition,
  ocr: ocrDefinition,
} satisfies Record<ComponentId, ComponentDefinition>
