// Generated by scripts/sync-component-catalog.mjs. Do not edit directly.
import { textTokensDefinition } from './text-tokens'
import { backgroundTokensDefinition } from './background-tokens'
import { borderTokensDefinition } from './border-tokens'
import { surfaceDefinition } from './surface'
import { buttonDefinition } from './button'
import { capsuleDefinition } from './capsule'
import { sliderDefinition } from './slider'
import { menuDefinition } from './menu'
import { actionDialogDefinition } from './action-dialog'
import { barDefinition } from './bar'
import { pageLayoutDefinition } from './page-layout'
import { cardToolBarDefinition } from './card-tool-bar'
import { baseCardDefinition } from './base-card'
import { componentPreviewCardDefinition } from './component-preview-card'
import { tagDefinition } from './tag'
import { chipButtonDefinition } from './chip-button'
import { markdownDefinition } from './markdown'
import { mdDefinition } from './md'
import { imageDefinition } from './image'
import { statDefinition } from './stat'
import { taggedCardDefinition } from './tagged-card'
import { ocrDefinition } from './ocr'
import type { ComponentId } from '../components-manifest'
import type { ComponentDefinition } from '../component-docs'

export const componentDefinitionsById = {
  'text-tokens': textTokensDefinition,
  'background-tokens': backgroundTokensDefinition,
  'border-tokens': borderTokensDefinition,
  surface: surfaceDefinition,
  button: buttonDefinition,
  capsule: capsuleDefinition,
  slider: sliderDefinition,
  menu: menuDefinition,
  'action-dialog': actionDialogDefinition,
  bar: barDefinition,
  'page-layout': pageLayoutDefinition,
  'card-tool-bar': cardToolBarDefinition,
  'base-card': baseCardDefinition,
  'component-preview-card': componentPreviewCardDefinition,
  tag: tagDefinition,
  'chip-button': chipButtonDefinition,
  markdown: markdownDefinition,
  md: mdDefinition,
  image: imageDefinition,
  stat: statDefinition,
  'tagged-card': taggedCardDefinition,
  ocr: ocrDefinition,
} satisfies Record<ComponentId, ComponentDefinition>
