// Generated compatibility catalog. Edit catalog/packages instead.
export const componentPackages = [
  { id: 'weimo-ui-core', title: 'weimo-ui-core' },
  { id: 'weimo-ui-tagtree', title: 'weimo-ui-tagtree' },
  { id: 'weimo-ui-markdown', title: 'weimo-ui-markdown' },
  { id: 'weimo-ui-image', title: 'weimo-ui-image' },
  { id: 'weimo-ui-stats', title: 'weimo-ui-stats' },
  { id: 'weimo-ui-card', title: 'weimo-ui-card' },
] as const

export type ComponentPackageName = (typeof componentPackages)[number]['id']

export type ComponentManifestItem = {
  id: string
  name: string
  exportName?: string
  registryName: string
  packageExport: string
  packageName: ComponentPackageName
  page: string
  docs: boolean
  registry: true
}

export const componentManifest = [
  {
    id: 'text-tokens',
    name: '文字样式',
    registryName: 'font-size',
    packageExport: './components/font-size',
    packageName: 'weimo-ui-core',
    page: 'text-tokens',
    docs: true,
    registry: true,
  },
  {
    id: 'text-color',
    name: '字色',
    registryName: 'text-color',
    packageExport: './components/text-color',
    packageName: 'weimo-ui-core',
    page: 'text-tokens',
    docs: false,
    registry: true,
  },
  {
    id: 'background-tokens',
    name: '背景样式',
    registryName: 'bg-color',
    packageExport: './components/bg-color',
    packageName: 'weimo-ui-core',
    page: 'background-tokens',
    docs: true,
    registry: true,
  },
  {
    id: 'bg-blur',
    name: '背景模糊度',
    registryName: 'bg-blur',
    packageExport: './components/bg-blur',
    packageName: 'weimo-ui-core',
    page: 'background-tokens',
    docs: false,
    registry: true,
  },
  {
    id: 'heat-color',
    name: '热力图色',
    registryName: 'heat-color',
    packageExport: './components/heat-color',
    packageName: 'weimo-ui-core',
    page: 'background-tokens',
    docs: false,
    registry: true,
  },
  {
    id: 'pressable',
    name: '按压反馈色',
    registryName: 'pressable',
    packageExport: './components/pressable',
    packageName: 'weimo-ui-core',
    page: 'background-tokens',
    docs: false,
    registry: true,
  },
  {
    id: 'border-tokens',
    name: '边框样式',
    registryName: 'border-color',
    packageExport: './components/border-color',
    packageName: 'weimo-ui-core',
    page: 'border-tokens',
    docs: true,
    registry: true,
  },
  {
    id: 'border-radius',
    name: '边框圆角',
    registryName: 'border-radius',
    packageExport: './components/border-radius',
    packageName: 'weimo-ui-core',
    page: 'border-tokens',
    docs: false,
    registry: true,
  },
  {
    id: 'surface',
    name: '材质',
    registryName: 'card-surface',
    packageExport: './components/card-surface',
    packageName: 'weimo-ui-core',
    page: 'surface',
    docs: true,
    registry: true,
  },
  {
    id: 'frosted-surface',
    name: 'FrostedSurface',
    registryName: 'frosted-surface',
    packageExport: './components/frosted-surface',
    packageName: 'weimo-ui-core',
    page: 'surface',
    docs: false,
    registry: true,
  },
  {
    id: 'liquid-glass',
    name: '液态玻璃',
    exportName: 'LiquidGlassSurface',
    registryName: 'liquid-glass',
    packageExport: './components/liquid-glass',
    packageName: 'weimo-ui-core',
    page: 'surface',
    docs: false,
    registry: true,
  },
  {
    id: 'popup-surface',
    name: 'PopupSurface',
    registryName: 'popup-surface',
    packageExport: './components/popup-surface',
    packageName: 'weimo-ui-core',
    page: 'surface',
    docs: false,
    registry: true,
  },
  {
    id: 'button',
    name: '按钮',
    exportName: 'TextButton',
    registryName: 'text-button',
    packageExport: './components/text-button',
    packageName: 'weimo-ui-core',
    page: 'button',
    docs: true,
    registry: true,
  },
  {
    id: 'frosted-icon-button',
    name: 'FrostedIconButton',
    registryName: 'frosted-icon-button',
    packageExport: './components/frosted-icon-button',
    packageName: 'weimo-ui-core',
    page: 'button',
    docs: false,
    registry: true,
  },
  {
    id: 'frosted-icon-button-group',
    name: 'FrostedIconButtonGroup',
    registryName: 'frosted-icon-button-group',
    packageExport: './components/frosted-icon-button-group',
    packageName: 'weimo-ui-core',
    page: 'button',
    docs: false,
    registry: true,
  },
  {
    id: 'ghost-icon-button',
    name: 'GhostIconButton',
    registryName: 'ghost-icon-button',
    packageExport: './components/ghost-icon-button',
    packageName: 'weimo-ui-core',
    page: 'button',
    docs: false,
    registry: true,
  },
  {
    id: 'mode-button',
    name: 'ModeButton',
    registryName: 'mode-button',
    packageExport: './components/mode-button',
    packageName: 'weimo-ui-core',
    page: 'button',
    docs: false,
    registry: true,
  },
  {
    id: 'capsule',
    name: '胶囊',
    exportName: 'Chip',
    registryName: 'chip',
    packageExport: './components/chip',
    packageName: 'weimo-ui-core',
    page: 'capsule',
    docs: true,
    registry: true,
  },
  {
    id: 'slider',
    name: '滑块',
    exportName: 'Slider',
    registryName: 'slider',
    packageExport: './components/slider',
    packageName: 'weimo-ui-core',
    page: 'slider',
    docs: true,
    registry: true,
  },
  {
    id: 'menu',
    name: '菜单',
    exportName: 'Menu',
    registryName: 'menu',
    packageExport: './components/menu',
    packageName: 'weimo-ui-core',
    page: 'menu',
    docs: true,
    registry: true,
  },
  {
    id: 'action-dialog',
    name: '对话框',
    exportName: 'ActionDialog',
    registryName: 'action-dialog',
    packageExport: './components/action-dialog',
    packageName: 'weimo-ui-core',
    page: 'action-dialog',
    docs: true,
    registry: true,
  },
  {
    id: 'bar',
    name: '浮动栏',
    exportName: 'FloatBar',
    registryName: 'float-bar',
    packageExport: './components/float-bar',
    packageName: 'weimo-ui-core',
    page: 'bar',
    docs: true,
    registry: true,
  },
  {
    id: 'bottom-bar',
    name: 'BottomBar',
    registryName: 'bottom-bar',
    packageExport: './components/bottom-bar',
    packageName: 'weimo-ui-core',
    page: 'bar',
    docs: false,
    registry: true,
  },
  {
    id: 'page-layout',
    name: '页面布局',
    exportName: 'SideBar',
    registryName: 'sidebar',
    packageExport: './components/sidebar',
    packageName: 'weimo-ui-core',
    page: 'page-layout',
    docs: true,
    registry: true,
  },
  {
    id: 'top-bar',
    name: 'TopBar',
    registryName: 'top-bar',
    packageExport: './components/top-bar',
    packageName: 'weimo-ui-core',
    page: 'page-layout',
    docs: false,
    registry: true,
  },
  {
    id: 'card-tool-bar',
    name: '卡片栏位',
    exportName: 'CardToolBar',
    registryName: 'card-tool-bar',
    packageExport: './components/card-tool-bar',
    packageName: 'weimo-ui-core',
    page: 'card-tool-bar',
    docs: true,
    registry: true,
  },
  {
    id: 'card-top-bar',
    name: 'CardTopBar',
    registryName: 'card-top-bar',
    packageExport: './components/card-top-bar',
    packageName: 'weimo-ui-core',
    page: 'card-tool-bar',
    docs: false,
    registry: true,
  },
  {
    id: 'base-card',
    name: '基础卡片',
    exportName: 'BaseCard',
    registryName: 'base-card',
    packageExport: './components/base-card',
    packageName: 'weimo-ui-core',
    page: 'base-card',
    docs: true,
    registry: true,
  },
  {
    id: 'component-preview-card',
    name: '预览卡片',
    exportName: 'ComponentPreviewCard',
    registryName: 'component-preview-card',
    packageExport: './components/component-preview-card',
    packageName: 'weimo-ui-core',
    page: 'component-preview-card',
    docs: true,
    registry: true,
  },
  {
    id: 'tag',
    name: '标签树',
    exportName: 'TagBar',
    registryName: 'tag-bar',
    packageExport: './components/tag-bar',
    packageName: 'weimo-ui-tagtree',
    page: 'tag',
    docs: true,
    registry: true,
  },
  {
    id: 'tag-bread',
    name: 'TagBread',
    registryName: 'tag-bread',
    packageExport: './components/tag-bread',
    packageName: 'weimo-ui-tagtree',
    page: 'tag',
    docs: false,
    registry: true,
  },
  {
    id: 'tag-picker',
    name: 'TagPicker',
    registryName: 'tag-picker',
    packageExport: './components/tag-picker',
    packageName: 'weimo-ui-tagtree',
    page: 'tag',
    docs: false,
    registry: true,
  },
  {
    id: 'tag-tree',
    name: 'TagTree',
    registryName: 'tag-tree',
    packageExport: './components/tag-tree',
    packageName: 'weimo-ui-tagtree',
    page: 'tag',
    docs: false,
    registry: true,
  },
  {
    id: 'tag-tree-row',
    name: 'TagTreeRow',
    registryName: 'tag-tree-row',
    packageExport: './components/tag-tree-row',
    packageName: 'weimo-ui-tagtree',
    page: 'tag',
    docs: false,
    registry: true,
  },
  {
    id: 'chip-button',
    name: '标签胶囊',
    exportName: 'ChipButton',
    registryName: 'chip-button',
    packageExport: './components/chip-button',
    packageName: 'weimo-ui-tagtree',
    page: 'chip-button',
    docs: true,
    registry: true,
  },
  {
    id: 'markdown',
    name: 'Markdown 编辑与预览',
    exportName: 'MdEditor',
    registryName: 'md-editor',
    packageExport: './components/md-editor',
    packageName: 'weimo-ui-markdown',
    page: 'markdown',
    docs: true,
    registry: true,
  },
  {
    id: 'math-editor',
    name: 'MathEditor',
    registryName: 'math-editor',
    packageExport: './components/math-editor',
    packageName: 'weimo-ui-markdown',
    page: 'markdown',
    docs: false,
    registry: true,
  },
  {
    id: 'md-render',
    name: 'MdRender',
    registryName: 'md-render',
    packageExport: './components/md-render',
    packageName: 'weimo-ui-markdown',
    page: 'markdown',
    docs: false,
    registry: true,
  },
  {
    id: 'md-view',
    name: 'MdView',
    registryName: 'md-view',
    packageExport: './components/md-view',
    packageName: 'weimo-ui-markdown',
    page: 'markdown',
    docs: false,
    registry: true,
  },
  {
    id: 'md',
    name: 'Markdown 样式',
    exportName: 'Md',
    registryName: 'md',
    packageExport: './components/md',
    packageName: 'weimo-ui-markdown',
    page: 'md',
    docs: true,
    registry: true,
  },
  {
    id: 'image',
    name: '图片',
    exportName: 'ImageView',
    registryName: 'image-view',
    packageExport: './components/image-view',
    packageName: 'weimo-ui-image',
    page: 'image',
    docs: true,
    registry: true,
  },
  {
    id: 'image-uploader',
    name: 'ImageUploader',
    registryName: 'image-uploader',
    packageExport: './components/image-uploader',
    packageName: 'weimo-ui-image',
    page: 'image',
    docs: false,
    registry: true,
  },
  {
    id: 'canvas-transparency',
    name: 'CanvasTransparency',
    registryName: 'canvas-transparency',
    packageExport: './components/canvas-transparency',
    packageName: 'weimo-ui-image',
    page: 'image',
    docs: false,
    registry: true,
  },
  {
    id: 'stat',
    name: '统计',
    exportName: 'StatGroup',
    registryName: 'stat-group',
    packageExport: './components/stat-group',
    packageName: 'weimo-ui-stats',
    page: 'stat',
    docs: true,
    registry: true,
  },
  {
    id: 'heatmap',
    name: 'Heatmap',
    registryName: 'heatmap',
    packageExport: './components/heatmap',
    packageName: 'weimo-ui-stats',
    page: 'stat',
    docs: false,
    registry: true,
  },
  {
    id: 'tagged-card',
    name: '带标签卡片',
    exportName: 'Card',
    registryName: 'card',
    packageExport: './components/card',
    packageName: 'weimo-ui-card',
    page: 'tagged-card',
    docs: true,
    registry: true,
  },
  {
    id: 'card-composer',
    name: 'CardComposer',
    registryName: 'card-composer',
    packageExport: './components/card-composer',
    packageName: 'weimo-ui-card',
    page: 'tagged-card',
    docs: false,
    registry: true,
  },
  {
    id: 'ocr',
    name: 'OCR',
    exportName: 'OcrCard',
    registryName: 'ocr-card',
    packageExport: './components/ocr-card',
    packageName: 'weimo-ui-card',
    page: 'ocr',
    docs: true,
    registry: true,
  },
  {
    id: 'ocr-composer',
    name: 'OcrComposer',
    registryName: 'ocr-composer',
    packageExport: './components/ocr-composer',
    packageName: 'weimo-ui-card',
    page: 'ocr',
    docs: false,
    registry: true,
  },
  {
    id: 'ocr-detail',
    name: 'OcrDetail',
    registryName: 'ocr-detail',
    packageExport: './components/ocr-detail',
    packageName: 'weimo-ui-card',
    page: 'ocr',
    docs: false,
    registry: true,
  },
] as const satisfies ComponentManifestItem[]

export type ComponentId = Extract<
  (typeof componentManifest)[number],
  { readonly docs: true }
>['id']
