// Generated by scripts/sync-component-catalog.mjs. Do not edit directly.
import { mdDefinition } from './md'
import { textTokensDefinition } from './text-tokens'
import { backgroundTokensDefinition } from './background-tokens'
import { borderTokensDefinition } from './border-tokens'
import { surfaceDefinition } from './surface'
import { actionDialogDefinition } from './action-dialog'
import { menuDefinition } from './menu'
import { buttonDefinition } from './button'
import { bottomBarDefinition } from './bottom-bar'
import { cardToolBarDefinition } from './card-tool-bar'
import { cardTopBarDefinition } from './card-top-bar'
import { floatBarDefinition } from './float-bar'
import { sidebarDefinition } from './sidebar'
import { topBarDefinition } from './top-bar'
import { tagDefinition } from './tag'
import { capsuleDefinition } from './capsule'
import { cardDefinition } from './card'
import { cardComposerDefinition } from './card-composer'
import { mathEditorDefinition } from './math-editor'
import { mdEditorDefinition } from './md-editor'
import { mdRenderDefinition } from './md-render'
import { mdViewDefinition } from './md-view'
import { canvasTransparencyDefinition } from './canvas-transparency'
import { imageUploaderDefinition } from './image-uploader'
import { imageViewDefinition } from './image-view'
import { ocrCardDefinition } from './ocr-card'
import { ocrComposerDefinition } from './ocr-composer'
import { ocrDetailDefinition } from './ocr-detail'
import { heatmapDefinition } from './heatmap'
import { statGroupDefinition } from './stat-group'
import type { ComponentId } from '../components-manifest'
import type { ComponentDefinition } from '../component-docs'

export const componentDefinitionsById = {
  md: mdDefinition,
  'text-tokens': textTokensDefinition,
  'background-tokens': backgroundTokensDefinition,
  'border-tokens': borderTokensDefinition,
  surface: surfaceDefinition,
  'action-dialog': actionDialogDefinition,
  menu: menuDefinition,
  button: buttonDefinition,
  'bottom-bar': bottomBarDefinition,
  'card-tool-bar': cardToolBarDefinition,
  'card-top-bar': cardTopBarDefinition,
  'float-bar': floatBarDefinition,
  sidebar: sidebarDefinition,
  'top-bar': topBarDefinition,
  tag: tagDefinition,
  capsule: capsuleDefinition,
  card: cardDefinition,
  'card-composer': cardComposerDefinition,
  'math-editor': mathEditorDefinition,
  'md-editor': mdEditorDefinition,
  'md-render': mdRenderDefinition,
  'md-view': mdViewDefinition,
  'canvas-transparency': canvasTransparencyDefinition,
  'image-uploader': imageUploaderDefinition,
  'image-view': imageViewDefinition,
  'ocr-card': ocrCardDefinition,
  'ocr-composer': ocrComposerDefinition,
  'ocr-detail': ocrDetailDefinition,
  heatmap: heatmapDefinition,
  'stat-group': statGroupDefinition,
} satisfies Record<ComponentId, ComponentDefinition>
