// Generated by scripts/sync-component-catalog.mjs. Do not edit directly.
import { mdDefinition } from './md'
import { textTokensDefinition } from './text-tokens'
import { backgroundTokensDefinition } from './background-tokens'
import { borderTokensDefinition } from './border-tokens'
import { surfaceDefinition } from './surface'
import { actionDialogDefinition } from './action-dialog'
import { menuDefinition } from './menu'
import { buttonDefinition } from './button'
import { barDefinition } from './bar'
import { tagDefinition } from './tag'
import { capsuleDefinition } from './capsule'
import { cardDefinition } from './card'
import { cardComposerDefinition } from './card-composer'
import { markdownDefinition } from './markdown'
import { ocrDefinition } from './ocr'
import { imageDefinition } from './image'
import { statDefinition } from './stat'
import type { ComponentId } from '../components-manifest'
import type { ComponentDefinition } from '../component-docs'

export const componentDefinitionsById = {
  md: mdDefinition,
  'text-tokens': textTokensDefinition,
  'background-tokens': backgroundTokensDefinition,
  'border-tokens': borderTokensDefinition,
  surface: surfaceDefinition,
  'action-dialog': actionDialogDefinition,
  menu: menuDefinition,
  button: buttonDefinition,
  bar: barDefinition,
  tag: tagDefinition,
  capsule: capsuleDefinition,
  card: cardDefinition,
  'card-composer': cardComposerDefinition,
  markdown: markdownDefinition,
  ocr: ocrDefinition,
  image: imageDefinition,
  stat: statDefinition,
} satisfies Record<ComponentId, ComponentDefinition>
